#' @import jsonlite scales dplyr tidyr

NULL 
#' @name json_to_paramter_list
#' @aliases json_to_paramter_list
#' @title Convert a JSON file to a list of parameters
#' @rdname json_to_paramter_list
#' @description This function converts a JSON file to a list of parameters.
#' @param json_file A JSON file containing the parameters
#' @return A list of parameters (invisible)
#' @export

json_to_paramter_list <- function(json_file) {
    invisible(as.relistable(jsonlite::fromJSON(json_file)))
}

NULL 
#' @name paramter_vec_to_list
#' @aliases paramter_vec_to_list
#' @title Convert a vector of parameters to a list of parameters (useful for calibrating parameters)
#' @rdname paramter_vec_to_list
#' @description This function converts a vector of parameters to a list of parameters.
#' @param parameter_vec A vector of parameters
#' @param prameter_skeleton A list of parameters to use as a skeleton for the new list
#' @return A list of parameters (invisible)
#' @export

paramter_vec_to_list <- function(parameter_vec, prameter_skeleton) {
    invisible(relist(parameter_vec, skeleton = prameter_skeleton))
}

NULL
#' @name model_diagnose
#' @aliases model_diagnose
#' @title Output the model diagnose information including estimated groundwater level, hn, xn, recharge and average recharge.
#' @param result The model estimated results. Generated by \code{\link{estimate_sgd}}.
#' @param obs_data The data.frame used as \code{inputData} in \code{\link{estimate_sgd}}.
#' @param start_date A valid string that can be transformed into data format using \code{ymd}.
#' @return A \code{ggplot} object.
#' @export

model_diagnosis <- function(result, obs_data, start_date) {
    plot_df <- result %>% 
      pivot_longer(cols = -t, values_to = 'pred') %>%
      mutate(date = ymd(start_date) - 1 + t) %>%
      mutate(name = factor(name, levels = c('wl', 'SGD', 'hn', 'xn', 'Wrechg', 'WrechgAve'),
                           labels = c('WL~(m~AHD)',
                                      'SGD~(m^3/d)',
                                      'h[n]~(m~AHD)',
                                      'x[n]~(m)',
                                      'w[recharge]~(mm)',
                                      'w[recharge[ave]]~(mm)'))) %>%
      left_join(obs_data, by = c('date', 'name'))
    ggplot(plot_df, aes(x = date, y = pred)) +
      geom_line(linewidth = 0.8) +
      geom_point(data = drop_na(plot_df), aes(y = obs, color = 'Observed Water Level'), size = 1.2) +
      geom_point(data = drop_na(plot_df), aes(y = pred, color = 'Estimated Water Level'), size = 1.2) +
      facet_wrap(~name, ncol = 1, strip.position = 'left',
                 labeller = label_parsed, scales = 'free_y') +
      scale_y_continuous(breaks = pretty_breaks(5),
                         labels = scales::label_number(accuracy = 0.01, scale_cut = cut_long_scale())) +
      scale_x_date(breaks = pretty_breaks(n = 10)) +
      scale_color_manual(name = NULL,
                         values = c('Observed Water Level' = 'red',
                                    'Estimated Water Level' = 'black')) +
      theme_bw(base_size = 12, base_family = 'serif') +
      theme(strip.placement = 'outside',
            strip.background = element_blank(),
            axis.text = element_text(color = 'black'),
            legend.position = 'bottom') +
      labs(x = 'Date', y = '')

  }