# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' Return a numeric vector of moving average with leading NAs filled with first average value
#'
#' @param x A numeric vector with no NAs
#' @param windowSize A integer of window size
#' @return A numeric vector of moving average with leading NAs filled with first average value
#' @name moving_average
NULL

