# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' 
NULL

#' 
#' Return a numeric vector of moving average with leading NAs filled with first average value
#' 
#' @param x A numeric vector with no NAs
#' @param windowSize A integer of window size
#' @return A numeric vector of moving average with leading NAs filled with first average value
moving_average <- function(x, windowSize) {
    .Call('_SGDr_moving_average', PACKAGE = 'SGDr', x, windowSize)
}

#' 
#' Calculate the surface water recharge using 1D model based on SWAT procedure
#' 
#' @param t A integer vector of simulation day
#' @param R A numeric vector of daily precipitation (mm)
#' @param E0 A numeric vector of daily potential evaporation calculated with Penman monteith method (mm)
#' @param H2O_SB1 A numeric vector of depth of water in SB1 (initial condition)
#' @param H2O_SB2 A numeric vector of depth of water in SB2 (initial condition)
#' @param params A list for parameters of the model
#' @param calibration If true return only the recharge value (for computational efficiency)
#' @return A data.frame with daily surface water recharge
cal_recharge <- function(t, R, E0, H2O_SB1, H2O_SB2, params, calibration) {
    .Call('_SGDr_cal_recharge', PACKAGE = 'SGDr', t, R, E0, H2O_SB1, H2O_SB2, params, calibration)
}

cal_sgd <- function(GWL, Wrechg, WrechgAve, Pumping, params, calibration) {
    .Call('_SGDr_cal_sgd', PACKAGE = 'SGDr', GWL, Wrechg, WrechgAve, Pumping, params, calibration)
}

